package com.nicearma.db;

public enum DBSql {

    CREATE_TABLE_IMAGE( "CREATE TABLE IF NOT EXISTS image  ( ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, url varchar(255), name varchar(255) )"),
    CREATE_TABLE_URL( "CREATE TABLE IF NOT EXISTS crawl  ( ID INTEGER auto_increment NOT NULL, url varchar(255), scanned boolean, CONSTRAINT url_unique PRIMARY KEY (url) )"),

    SELECT_URL("SELECT url FROM crawl"),
    SELECT_URL_SCANNED_STATUS("SELECT url FROM crawl WHERE scanned= ?"),

    INSERT_FOUND_URL("MERGE INTO crawl (url,scanned) values (?, false)");


    private String sql;

    DBSql(String sql) {
        this.sql = sql;
    }

    public String getSql() {
        return sql;
    }

    public void setSql(String sql) {
        this.sql = sql;
    }
}
